name: Check Patches for Rejects

on:
  workflow_dispatch:
  workflow_call:
  pull_request:
  push:
    paths-ignore:
      - 'README.md'
  schedule:
   - cron: "0 10 * * *"

jobs:
  ksu:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        ksu:
          - name: KSUN
            repo_url: "https://github.com/KernelSU-Next/KernelSU-Next"
            repo_owner: "KernelSU-Next"
            repo: "KernelSU-Next"
            branch: "next"
            patch: "KSUN/KSUN-SUSFS-1.5.9.patch"
          - name: RKSU
            repo_url: "https://github.com/rsuntk/KernelSU"
            repo_owner: "rsuntk"
            repo: "KernelSU"
            branch: "main"
            patch: "RKSU/RKSU-SUSFS-1.5.9.patch"

    steps:
      - name: Patch KernelSU with SUSFS patch
        run: |
          set -e

          git clone --depth=1 "https://github.com/${{ github.repository }}" "patch"

          git clone --depth=1 "https://github.com/TheSillyOk/sh" "sh"
          KSU_V=$(bash sh/get_ksuver.sh "${{ matrix.ksu.repo_owner }}" "${{ matrix.ksu.repo }}" "${{ matrix.ksu.branch }}")
          echo "--- Cloning and patching ${{ matrix.ksu.name }} $KSU_V ---"

          git clone --depth=1 "${{ matrix.ksu.repo_url }}" -b ${{ matrix.ksu.branch }} "KSU"
          cd KSU
          patch -p1 -F 3 -N < "../patch/${{ matrix.ksu.patch }}"


  kernel:
    needs: ksu
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build_type: ["RKSU", "KSUN"]
        susfs: [true]
        kernel_config:
          - kernel_name: "SM6125"
            tag: SM6125
            kernel_url: "https://github.com/LineageOS/android_kernel_xiaomi_sm6125"
            defconfig: "vendor/trinket-perf_defconfig"
            config: "vendor/xiaomi-trinket.config vendor/laurel_sprout.config"
            patches_folder: "sm6125"
        exclude:
          - build_type: "Normal"
            susfs: true

    permissions:
      contents: write

    steps:
      - name: Set Environment Variables
        id: vars
        run: |
          echo "defconfig=${{ matrix.kernel_config.defconfig || 'vendor/laurel_sprout-perf_defconfig' }}" >> $GITHUB_ENV
          echo "config=${{ matrix.kernel_config.config }}" >> $GITHUB_ENV
          echo "patches_url=${{ matrix.kernel_config.patches_url || 'https://github.com/TheSillyOk/kernel_ls_patches' }}" >> $GITHUB_ENV
          echo "patches_branch_arg=${{ matrix.kernel_config.patches_branch && format('-b {0}', matrix.kernel_config.patches_branch) || '' }}" >> $GITHUB_ENV
          echo "patches_folder=${{ matrix.kernel_config.patches_folder || 'noname' }}" >> $GITHUB_ENV
          echo "kernel_branch_arg=${{ matrix.kernel_config.kernel_branch && format('-b {0}', matrix.kernel_config.kernel_branch) || '' }}" >> $GITHUB_ENV
          echo "susfs_branch=${{ matrix.kernel_config.susfs_branch || 'kernel-4.14' }}" >> $GITHUB_ENV
          echo "device=${{ matrix.kernel_config.device || 'MiA3' }}" >> $GITHUB_ENV
          echo "python3=${{ matrix.kernel_config.python3_patch || 'false' }}" >> $GITHUB_ENV

      - name: Initialize Workspace and Install Tools
        run: |
          echo "workspace_folder=${GITHUB_WORKSPACE}/workspace" >> $GITHUB_ENV
          mkdir -p "${GITHUB_WORKSPACE}/workspace"
          sudo apt-get update -qq
          sudo apt-get install -y --no-install-recommends python3-pip git zip unzip gcc g++ make ninja-build file bc bison flex libfl-dev libssl-dev libelf-dev wget build-essential python3-dev python3-setuptools rsync ccache llvm-dev libncurses6 libfdt-dev
          sudo curl -L https://raw.githubusercontent.com/kadwanev/retry/master/retry -o /usr/local/bin/retry && sudo chmod +x /usr/local/bin/retry

      - name: Cache Clang
        uses: actions/cache@v4
        id: cache-clang
        with:
          path: ${{ env.workspace_folder }}/clang
          key: clang-r547379-ubuntu-latest

      - name: Download and Extract Clang
        if: steps.cache-clang.outputs.cache-hit != 'true'
        working-directory: ${{ env.workspace_folder }}
        run: |
          retry -t 3 -s 5 "wget https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+archive/refs/heads/main/clang-r547379.tar.gz -O clang.tar.gz"
          mkdir -p clang && tar -xf clang.tar.gz -C clang

      - name: Set up ccache
        run: |
          ccache --max-size=2G
          ccache --set-config=compression=true
          echo "CCACHE_DIR=$HOME/.ccache" >> $GITHUB_ENV

      - name: Cache Kernel Build
        uses: actions/cache@v4
        with:
          path: ~/.ccache
          key: ${{ env.device }}-${{ matrix.build_type }}-${{ matrix.kernel_config.tag }}-SUSFS_${{ matrix.susfs }}-ccache-${{ github.sha }}-${{ github.run_number }}
          restore-keys: |
            ${{ env.device }}-${{ matrix.build_type }}-${{ matrix.kernel_config.tag }}-SUSFS_${{ matrix.susfs }}-ccache-${{ github.sha }}
            ${{ env.device }}-${{ matrix.build_type }}-${{ matrix.kernel_config.tag }}-SUSFS_${{ matrix.susfs }}-ccache-

      - name: Prepare Kernel Source
        run: |
          set -e
          echo "kernel_folder=${{ env.workspace_folder }}/kernel_tree" >> $GITHUB_ENV
          git clone --depth=1 "${{ matrix.kernel_config.kernel_url }}" ${{ env.kernel_branch_arg }} "${{ env.workspace_folder }}/kernel_tree"
          
          echo "patches_dir=${{ env.workspace_folder }}/kernel_patches" >> $GITHUB_ENV
          git clone --depth=1 "${{ env.patches_url }}" ${{ env.patches_branch_arg }} "${{ env.workspace_folder }}/kernel_patches"

          cd "${{ env.workspace_folder }}/kernel_tree"
          if ${{ env.python3 }}; then
            patch -p1 -F 3 -N < "${{ env.workspace_folder }}/kernel_patches/python3.patch" || true
          fi
          
          for patch_name in fix_lto ptrace_fix; do
            patch -p1 < "${{ env.workspace_folder }}/kernel_patches/${patch_name}.patch" || true
          done

          sed -i 's/-dirty//' ./scripts/setlocalversion
          sed -i -E 's/^(CONFIG_LOCALVERSION=.*)/\1-Ok/gi' "arch/arm64/configs/${{ env.defconfig }}"
          echo -e "\n\n# Workflow added configs #\nCONFIG_MODVERSIONS=n" >> "arch/arm64/configs/${{ env.defconfig }}"

      - name: Apply KernelSU / Forks
        if: matrix.build_type != 'Normal'
        working-directory: ${{ env.kernel_folder }}
        run: |
          set -e
          case "${{ matrix.build_type }}" in
            KSU)
              curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s v0.9.5
              for patch_name in path_unmount get_cred_rcu strncpy_from_user_nofault ${{ env.patches_folder }}/manual_hooks; do
                patch -p1 -F 3 -N < "${{ env.patches_dir }}/${patch_name}.patch"
              done
              ;;
            KSUN)
              curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next/kernel/setup.sh" | bash -s next
              patch -p1 -F 3 -N < "${{ env.patches_dir }}/KSUN/syscall_hooks.patch"
              cd KernelSU-Next
              patch -p1 -F 3 -N < "${{ env.patches_dir }}/KSUN/WildJames-Manager.patch"
              ;;
            RKSU)
              curl -LSs "https://raw.githubusercontent.com/rsuntk/KernelSU/main/kernel/setup.sh" | bash -s main
              for patch_name in path_unmount get_cred_rcu strncpy_from_user_nofault KSUN/syscall_hooks; do
                patch -p1 -F 3 -N < "${{ env.patches_dir }}/${patch_name}.patch"
              done
              ;;
          esac

          cd ${{ env.kernel_folder }}
          sed -i -E 's/^CONFIG_(KPROBES|TMPFS_XATTR|KSU[^=]*)=(y|n)/# CONFIG_\1=\2/g' "arch/arm64/configs/${{ env.defconfig }}"
          echo -e "\nCONFIG_KPROBES=n\nCONFIG_KSU=y\nCONFIG_TMPFS_XATTR=y\n" >> "arch/arm64/configs/${{ env.defconfig }}"

      - name: Apply SUSFS
        if: matrix.susfs
        working-directory: ${{ env.kernel_folder }}
        run: |
          set -e
          SUSFS_FOLDER="${{ env.workspace_folder }}/susfs4ksu"
          git clone --depth=1 https://gitlab.com/simonpunk/susfs4ksu.git -b "${{ env.susfs_branch }}" "$SUSFS_FOLDER"

          case "${{ matrix.build_type }}" in
            KSU)
              patch -p1 -F 3 -N < "$SUSFS_FOLDER/kernel_patches/50_add_susfs_in_${{ env.susfs_branch }}.patch" || true
              patch -p1 -F 3 -N < "${{ env.patches_dir }}/${{ env.patches_folder }}/fix_susfs_rejects.patch" || true
              cp -r $SUSFS_FOLDER/kernel_patches/fs/* fs/
              cp -r $SUSFS_FOLDER/kernel_patches/include/linux/* include/linux
              cd KernelSU
              patch -p1 -F 3 -N < "$SUSFS_FOLDER/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch"
              ;;
            RKSU|KSUN)
              patch -p1 -F 3 -N < "${{ env.patches_dir }}/susfs-1.5.9.patch" || true
              cd KernelSU*
              patch -p1 -F 3 -N < "${{ env.patches_dir }}/${{ matrix.build_type }}/${{ matrix.build_type }}-SUSFS-1.5.9.patch"
              ;;
          esac

      - name: Build Kernel
        working-directory: ${{ env.kernel_folder }}
        run: |
          set -e

          EXTRA_FOLDER="${{ env.kernel_folder }}/extra"
          git clone --depth=1 https://github.com/TheSillyOk/kernel_extra -b main "$EXTRA_FOLDER"

          export CCACHE_EXEC=$(which ccache)
          export ARCH=arm64
          export SUBARCH=arm64
          export KBUILD_BUILD_USER="Ok"
          export KBUILD_BUILD_HOST="Github"
          export PATH="${{ env.workspace_folder }}/clang/bin:$PATH"
          
          mkdir -p "out/arch/arm64/boot/dts/xiaomi/.ginkgo-trinket-overlay.dtbo.qcom-base"
          
          make O=out ARCH=arm64 ${{ env.defconfig }} ${{ env.config }}
          make O=out DTC_PREBUILT=true DTC=$EXTRA_FOLDER/dtc DTC_OVERLAY_TEST_EXT=$EXTRA_FOLDER/ufdt_apply_overlay MKDTIMG=$EXTRA_FOLDER/mkdtimg CC="ccache clang" LD=ld.lld LLVM=1 LLVM_IAS=1 -j"$(nproc --all)" CROSS_COMPILE=aarch64-linux-gnu-
